# https://github.com/iamawatermelo/wakapi-anyide v0.6.8

[meta]
version = 1
watchers = ['files']

[files]
include = ["*"]  # files to include in tracking
exclude = []  # files to exclude in tracking
exclude_files = [".gitignore"]  # files whose contents will be used to exclude other files from tracking
exclude_binary_files = true  # whether to ignore binary files
# language_mapping = {".kicad_sch" = "Kicad Schematic"} # custom language mapping

[project]
name = "AirPodsLikeNormal"  # your project name